import Head from "next/head";

export default function PrototypeBeta() {
  return (
    <>
      <Head>
        <title>NYC Heat Recovery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Beta Prototype/Scale Model</h1>

        <section className="section">
          <h2>Overview</h2>
          <p>
            Our Beta prototype is different than the traditional Mechanical
            Engineering Design Project in that we are designing a large scale
            infrastructure system which can not be easily prototyped. Instead,
            we are creating a scale model which will display the general layout
            of our design in our case study as well as functionally showing the
            key process that moves the heat from the MTA&apos;s system to the
            buildings water system.
            <br />
            <br />
            The model will include functional electronic and fluid systems. Our
            fluid system will consist of two loops representing the MTA side and
            residential building side. We are using model scale piping, pumps,
            and fittings to create these loops. Our electronic system,
            controlled by an Arudino Uno, will power and control the pumps,
            lights, fans, and other small electric devices in our model.
          </p>
        </section>

        <section className="section">
          <h2>Design in SolidWorks</h2>
          <span className="flex space-x-8 [&>*]:w-1/2">
            <img
              src="/images/beta/solidworksDesign.png"
              alt="solidworks design"
            />
            <p>
              In order to make sure our model equipment fits together well, a
              Solidworks assembly was created to visualize how the various model
              components would fit together.
            </p>
          </span>
        </section>

        <section className="section">
          <h2>Façade Construction</h2>
          <span className="flex space-x-8 [&>*]:w-1/2">
            <p>
              As with any scale model, the façade is an important aspect so that
              viewers are able to visualize how the system would look in real
              life. The team wanted to represent the MTA ancillary building,
              where our heat is sourced from, as well as the residential
              building which will be receiving the heat.
              <br />
              <br />
              The &quot;ground&quot; was constructed out of polystyrene foam,
              which we cut into to place our hardware. The exception to this is
              the residential building basement, which was composed of plywood
              sidewalls and ceiling. The buildings were framed with wood and
              then covered in lasercut balsawood and basswood. 3D printed
              details, such as the balconies and windows, were pasted on after.
            </p>
            <img
              src="/images/beta/facadeConstruction.jpg"
              alt="facade construction"
            />
          </span>
        </section>

        <section className="section">
          <h2>Fluid System</h2>
          <span className="flex space-x-8 [&>*]:w-1/2">
            <p>
              The fluid system is the core functional component of our scale
              model. the team wanted to represent how the heat would flow in two
              distinct loops from the MTA side to the residential building side.
              The piping, fittings, radiators, pumps, and other associated
              hardware were supplied by manufacturers that focus on custom PC
              watercooling components as the scale of those was the perfect size
              for the model. For the purposes of the model, heat is supplied
              into the system by a resistive heater through a radiator, where
              the fluid then moves to our model heat pump. The heat pump
              transfers the heat to the residential loop, where a second
              radiator expels the heat back into the air.
              <br />
              <br />
              The picture on the right shows our test loop to verify the flow
              rate and test some of the heating and cooling components.
            </p>
            <img src="/images/beta/fluidSystem.jpg" alt="fluid system" />
          </span>
        </section>

        <section className="section">
          <h2>Model Heat Pump</h2>
          <span className="flex space-x-8 [&>*]:w-1/2">
            <p>
              A full scale heat pump, such as the one that would be implemented
              in our real system, utilizes an internal refrigeration circuit to
              transfer heat between one side and the other. That system was too
              be implemented into our scale model, so the team designed and
              manufactured a custom water-to-water heat pump using
              thermoelectric plates. Thermoelectric plates are electrical
              devices which produce cold temperatures on one side and hot
              temperatures on the other. We designed a water block (top right)
              which would connect to our fluid loops using custom fittings
              (bottom right). The water blocks transfer the heat between the
              fluid and the thermoelectric plates.
            </p>
            <img src="/images/beta/heatPumpModel.jpg" alt="heat pump" />
          </span>
        </section>

        <div className="w-[60%] max-w-[60%] flex flex-wrap justify-between [&>*]:h-[35vh]">
          <img src="/images/beta/feature1.jpg" alt="feature image 1" />
          <span className="w-1/2 flex justify-between">
            <img src="/images/beta/feature2.jpg" alt="feature image 2" />
            <img src="/images/beta/feature3.jpg" alt="feature image 3" />
          </span>
        </div>

        <section className="section">
          <h2>Electronics</h2>
          <span className="flex space-x-8 [&>*]:w-1/2">
            <p>
              All of the electronics in our scale model, including the lights,
              pumps, fans, sensors, and thermoelectric plates are all controlled
              by an Arduino Uno. The devices operate on various voltages ranging
              from 3.3V to 12V, so several supporting electrical components were
              needed such as relays, MOSFETs, potentiometers, and others. One
              Arduino program was created that would simultaneously collect
              temperature data, display it, as well as control the lights and
              fans.
            </p>
            <img src="/images/beta/electronics.jpg" alt="electronics" />
          </span>
        </section>
      </main>
    </>
  );
}
