import Head from "next/head";

export default function Design() {
  return (
    <>
      <Head>
        <title>NYC Heat Recovery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>System Design & Technical Analysis</h1>
        <section className="section">
          <h3>Heat Exchanger Series</h3>
          <p>
            In order to transfer heat from the MTA Chiller Loop and the Hot
            Water Distribution Line into the Building, a sequence of heat
            exchangers was constructed as shown in the schematic below. These
            two loops come into contact via a heat pump. One stream of hot water
            leaves the heat pump and travels through a series of heat exchangers
            to eventually end back into the pump. The second stream of water is
            drawn from the city domestic water supply and loops into each heat
            exchanger in the opposite direction to create a counter flow. After
            traveling through the full series of heat exchangers, the stream is
            sent to the hot water storage tanks in the building.
          </p>
        </section>
        <section className="section">
          <div className="w-full">
            <p className="italic">First Law of Thermodynamics</p>
            <p>
              The first law of thermodynamics was employed for this analysis
              using the following assumptions:
            </p>
            <ul>
              <li>Steady state analysis</li>
              <li>
                Heat loss was negligible (accounted for in efficiency of heat
                exchangers)
              </li>
              <li>Work was negligible over the control volume</li>
              <li>
                Difference in velocities of inlet and outlet stream was
                negligible
              </li>
              <li>Vertical displacement was negligible</li>
            </ul>
            <p>
              Using these assumptions, a calculator and model in Google Sheets
              was developed. The two fundamental equations for heat transfer in
              an exchanger were used and are shown below. One is based on the
              properties of the fluids including temperature, specific heat, and
              mass flow rate, while the other is based more on the properties of
              the heat exchanger including its heat transfer area and heat
              transfer coefficient U. The equations were setup using the
              counterflow conditions where the hot liquid enters on the same
              side where the cold liquid exits. A figure of this can also be
              seen below.
            </p>
          </div>
        </section>

        <section className="section">
          <img src="/images/equation.png" alt="equation" />
          <img src="/images/counterflow.png" alt="heat counterflow" />
        </section>

        <section className="section">
          <div>
            <p className="italic">Analysis</p>
            <p>
              Using the first law of thermodynamics, a control volume of a
              counterflow heat exchanger was modeled in order to determine the
              output temperature of the water stream into the building. The team
              created the heat exchanger model using inputs that could be found
              on the website of heat exchanger manufacturers, such as surface
              area, and a rater heat transfer at a given volumetric flow rate
              and temperature differential. Those inputs would allowed the heat
              transfer coefficient to be found, which was then applied to our
              own system.
            </p>
            <p>
              As seen below, a series of three counterflow heat exchangers were
              modeled to transfer heat between the intermediary loop from the
              heat pump and our building water supply. Given inputs of the cold
              building water supply and the hot water coming from the heat pump,
              as well as the mass flow rates of both loops, we can determine the
              temperature increase of the building water supply using our
              calculator.
            </p>
          </div>
        </section>

        <section className="section">
          <img src="/images/transferMap.jpg" alt="map of heat transfer" />
        </section>

        <section className="section">
          <div>
            <p className="italic">Purpose</p>
            <p>
              The calculator, which is shown below, is meant to streamline the
              process of choosing a proper heat exchanger. Because the team will
              not be designing our own heat exchanger, the model must rely on
              the specifications given by manufacturers. The goal of the
              calculator was to use the most common specifications given by the
              heat exchanger manufacturers to figure out the heat transfer
              properties of the unit and in turn model how our system&apos;s fluids
              will change in temperature at each state. We have a functioning
              model of this, which can be seen in the top right corner of the
              figure below. The temperature at each point in the heat exchanger
              loop can be found for both the intermediary and building supply
              loop.
            </p>
          </div>
        </section>

        <section className="section">
          <img src="/images/excelSheet.png" alt="excel sheet" />
        </section>

        <section className="section">
          <h2>Heat Loss through a Pipe</h2>
          <p>
            Heat loss from traversing through the pipe is expected as the water
            moves from the MTA ancillary buildings to receiving buildings. In
            order to calculate this heat loss, three-dimensional heat transfer
            equations were employed. Some variables within these equations have
            not yet been given to us by the MTA, namely the temperature and flow
            rate of the water as it enters the MTA ancillary building, so these
            variables were assumed to be 20°C and 2.5 m/s respectively as of
            now. As for other assumptions made for these calculations, we assume
            that all piping in New York City is to run parallel and
            perpendicular to streets and that all piping runs at a minimum of
            3.5 feet below the surface. Using the following two equations, we
            are able to determine the conduction shape factor for each receiving
            building with reference to its closest MTA ancillary building:
          </p>
        </section>

        <section className="section">
          <img
            src="/images/sVertHorFormula.png"
            alt="formula for sVert and sHor"
          />
        </section>

        <section className="section">
          <p>
            Where L represents the length of the pipe, D represents the pipe
            diameter, and z represents the depth of the pipe. As stated above,
            New York City mandates that all piping run at a depth of 3.5 feet,
            giving us our assumed z value. The underground pipe length is
            determined geometrically, using a scaled map of New York City we are
            able to determine the length of pipe that must run both parallel and
            perpendicular to the streets of the city. We may then, from this
            conduction shape factor, calculate the heat loss from the pipe at
            that particular section (vertical or horizontal) using the equation:
          </p>
        </section>

        <section className="section">
          <img src="/images/qFormula.png" alt="formula for Q" />
        </section>

        <section className="section">
          <p>
            As stated above, the temperature of the water is assumed to be
            initially 20 degrees Celsius. The other two variables rely on the
            properties of the soil of New York City. New York is known for
            employing Honeoye soil, however the city specifically uses fine
            sandy loam soil. The temperature of this soil varies with each
            month, typically averaging at 9.95°C, and the thermal conductivity
            of sandy loam soil, K, ranges between 0.37 and 1.42 W/mK, with fine
            sandy loam being on the higher end of that range. For the purposes
            of our calculations, we assume that the thermal conductivity of this
            soil is 1.2 W/mK.
          </p>
          <p>
            Once we calculate the heat loss at each section of the pipe using
            the following calculations, we are able to determine the total
            temperature drop of the water as it flows through the pipe using the
            following calculation:
          </p>
        </section>

        <section className="section">
          <img src="/images/qTotalFormula.png" alt="formula for q total" />
        </section>

        <section className="section">
          <div className="w-full">
            <p>
              Where V represents the flow rate of water, and we are able to
              determine the density and specific heat of water from the
              Properties of Saturated Water tables based on the temperature of
              the water at the inlet. These equations were then developed into a
              MATLAB program to speed up the processes, as well as allow us to
              manipulate the equations to find the following:
            </p>

            <ul>
              <li>
                Which building would experience the least amount of heat loss
                from an MTA ancillary building.
              </li>
              <li>
                What is the temperature drop of water between the MTA ancillary
                building and the receiving building.
              </li>
              <li>
                What is the ideal pipe diameter to prevent as much heat loss as
                possible.
              </li>
            </ul>
          </div>
        </section>

        <section className="section">
          <h2>Financial Analysis</h2>
          <p>
            The buildings chosen for consideration in the project can be
            evaluated using information from the{" "}
            <a
              href="https://www.be-exchange.org/calculator/"
              target="_blank"
              rel="noopener noreferrer"
            >
              NYC LL97 Carbon Calculator
            </a>
            . The CO2 emission threshold set by LL97 varies depending on
            parameters of each build, but by implementing the new DHW system in
            this project each building would be able to meet net carbon
            emissions below the pre-2030 threshold. 14% of the total energy
            usage of buildings is consumed by hot water heating.
          </p>
        </section>

        <section className="section">
          <img src="/images/buildingInfo.PNG" alt="building info table" />
        </section>

        <section className="section">
          <p>
            The project would be treated as a pilot program to prove
            applicability and help support the growth of the systems throughout
            NYC. The potential DHW savings included in the analysis are
            specifically for the pilot project. If the pilot is a success and
            the project would be expanded to different sites, the hot water
            provided by the MTA system would come with a cost to the customers.
            The cost for the DHW provided would be determined at a later date as
            the total project cost would need to be considered to find the
            breakeven for those funding the project. To help offset the costs of
            the pilot project, the group has researched and considered applying
            for a NYSERDA grant along with a partnership between the MTA,
            Highmark NY, and an engineering firm. 250 East 87th St is at the
            lowest demand for emission reduction as of right now, but starting
            in 2030 the carbon emissions from the building will be higher then
            the LL97 threshold and the building will need to consider efforts to
            reduce their CO2 emissions. From this analysis, The Camargue is in
            the greatest need of this system to help cut its CO2 emissions as it
            will met with the highest penalty from LL97 starting in 2024. The
            analysis shows that implementing the MTA DHW system would help each
            building meet the CO2 emission threshold set by LL97 for 2024-2029
            along with cutting the costs of the DHW heating for the building.
          </p>
        </section>

        <section className="section">
          <h2>System Design Parameters</h2>
          <div className="flex w-full [&>*]:w-1/2 space-x-8">
            <span>
              <p>
                The team used a tool called{" "}
                <a
                  href="https://ecosizer.ecotope.com/sizer/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  The Ecosizer{" "}
                </a>
                by Ecotope Engineering to simulate a heat pump hot water system
                against a known hot water load. The tool generates representing
                the trade off between Heat Pump Capacity and Storage Volume.
                Through this simulation, the team selected the following
                parameters:
              </p>

              <ul>
                <li>680 Kbtu/h for the primary heat pump</li>
                <li>210 Kbtu/h for the seconday heat pump</li>
                <li>4,200 gallons for primary storage</li>
                <li>200 gallons for secondary storage</li>
              </ul>
            </span>
            <img
              src="/images/primarySizingCurve.png"
              alt="primary sizing curve"
            />
          </div>
        </section>

        <section className="section">
          <h2>Final System Layout</h2>
          <div className="flex w-full [&>*]:w-1/2 space-x-8">
            <span>
              <p>
                The proposed system stems off of the MTA&apos;s water loop, running
                up to the Ancillary Building. This water is diverted to two heat
                pumps, the primary and secondary. The primary loop warms potable
                water through a heat exchanger, and the secondary maintains a
                storage tank at 150 degrees. Keeping a second, smaller tank at a
                higher temperature increases the energy density of the system,
                and minimizes the required volume.
              </p>
            </span>
            <img
              src="/images/303East83rdStSystem.jpg"
              alt="303 east 83rd st system"
            />
          </div>
        </section>
      </main>
    </>
  );
}
