import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>NYC Heat Recovery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <div className="banner">
          <div className="overlay"></div>
          <h1>Decarbonizing New York City with Heat Recovery</h1>
        </div>

        <section className="section">
          <h2>Mission Statement</h2>
          <p className="font-bold text-center">
            Our team is working hard to build New York City&apos;s first ever
            transit heat recovery system to providing a clean source of heat and
            eliminate carbon emissions.{" "}
          </p>
          <img src="/images/missionLogo.png" alt="mission logo" />
        </section>
        <section className="section">
          <h2>Stakeholders</h2>
          <div className="w-full h-fit img-col-2">
            <span>
              <img src="/images/stevensLogo.png" alt="stevens logo" />
              <div>
                <h3>Stevens Institute of Technology</h3>
                <p>
                  Stevens Institute of Technology&apos;s Senior Design class
                  lays out deliverables regularly.
                </p>
              </div>
            </span>
            <span>
              <img src="/images/MTALogo.png" alt="mta logo" />
              <div>
                <h3>Metropolitan Transportation Authority</h3>
                <p>
                  The MTA has the possibility to monetize excess heat and
                  provide buildings with alternate energy sources.
                </p>
              </div>
            </span>
          </div>

          <div className="w-full h-fit img-col-2">
            <span>
              <img
                src="/images/equityResident.png"
                alt="equity residential picture"
              />
              <div>
                <h3>Equity Residential</h3>
                <p>
                  <i>303 East 83rd Street</i>
                  <br />
                  <br />
                  Equity Residential can benefit from reduced carbon emissions,
                  LL97 Fine reductions, and energy costs.
                </p>
              </div>
            </span>
            <span>
              <img src="/images/highmarkLogo.png" alt="highmark logo" />
              <div>
                <h3>Highmark</h3>
                <p>
                  Highmark is sponsoring the team and sets technical goals for
                  the team to accomplish.
                </p>
              </div>
            </span>
          </div>
        </section>

        <section className="section">
          <h2>Have any questions?</h2>
          <p>
            Contact <a href="mailto:dmaggio@stevens.edu">dmaggio@stevens.edu</a>{" "}
            to get more information on the project
          </p>
        </section>
      </main>
    </>
  );
}
