import Head from "next/head";

export default function NYSERDA() {
  return (
    <>
      <Head>
        <title>NYC Heat Recovery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>NYSERDA APPLICATION GUIDE: PON#4614 CATEGORY B & C</h1>

        <section className="section">
          <h2>Description</h2>
          <p>
            Page PON 4614 is a program by NYSERDA (New York State Energy
            Research and Development Authority) that provides funding for
            community-style heat pump systems and MicroGrid design studies in
            New York State. Category B of the program funds site-specific design
            studies and Category C funds site specific implementation project.{" "}
          </p>
        </section>

        <section className="section">
          <h2>Category B</h2>
          <p>
            Category B, which refers to Site-Specific Design Studies. In this
            category, proposers can receive up to $500,000 in funding from
            NYSERDA to refine a single preferred design for a community heat
            pump system that appears technically and economically feasible.
          </p>
        </section>

        <section className="section h-[50vh]">
          <h2>Eligibility Criteria Category B</h2>
          <iframe
            className="w-4/6 h-full"
            src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRK1-DEgl8p4-fNLB1-wV0WdR0RPgBuZVyq_ZVFc0WWoYANTyoAk6EsrGkHbwlJJr8rcOHvGITUsHmA/pubhtml?gid=1585526791&amp;single=true&amp;widget=true&amp;headers=false"
          ></iframe>
        </section>

        <section className="section">
          <h2>Supporting Documents Category B</h2>
          <ul>
            <li>
              <a
                href="https://drive.google.com/file/d/1YhYvcC_2UDCwAVLaeaqBaTZSGN0eapYR/view?usp=share_link"
                target="_blank"
                rel="noopener noreferrer"
              >
                Attachment B Category B Instructions
              </a>
              : Attachment B is a section of Program Opportunity Notice (PON)
              4614 for Community Heat Pump Systems that outlines Category B,
              which refers to Site-Specific Design Studies.
            </li>
            <li>
              <a
                href="https://drive.google.com/file/d/18zEypCpyZJ9a6314u96HzEwpK6QWBwS9/view?usp=share_link"
                target="_blank"
                rel="noopener noreferrer"
              >
                Attachment B1 Category B Final Report Requirements
              </a>
              : The document outlines the requirements for a final report that
              will be posted on the New York State Energy Research and
              Development Authority (NYSERDA) website. The report is expected to
              address several questions related to the proposed community,
              technology, analytical methods, system design, business model, and
              impact of the project. The report should also include construction
              specifications, bid specs, and an investment-grade analysis of the
              economics associated with implementing/operating the system.
            </li>
            <li>
              <a
                href="https://drive.google.com/file/d/1m2ytx7fuYWv-mAU-w5M8PEI_Yikiyv1L/view?usp=share_link"
                target="_blank"
                rel="noopener noreferrer"
              >
                Summary
              </a>
            </li>
            <li>
              <a
                href="https://drive.google.com/file/d/1Fcb0RKlwd2ZfU4iqCqUOz0jlv8WC4i1x/view?usp=share_link"
                target="_blank"
                rel="noopener noreferrer"
              >
                Summary Revised
              </a>
            </li>
          </ul>
        </section>

        <section className="section">
          <h2>Category C</h2>
          <p>
            Category C, which refers to a site-specific implementation project
            is intended to construct, commission, and operate a community-style
            heat pump system serving a specific cluster of buildings.
            Site-Specific Implementation Project (NYSERDA&apos;s maximum funding
            for any award under Category C will be $4,000,000. Proposer cost
            share at or above 50% of total project cost very strongly
            preferred.)
          </p>
        </section>

        <section className="section h-[50vh]">
          <h2>Eligibility Criteria Category C</h2>
          <iframe
            className="w-4/6 h-full"
            src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQ3p7b5TcWj32uT46U6Pdz7nxiNHm1It9Lf1B8muWFxO8p-Nfvs46aod1kmhz1lgrZ_UORc8rTZFiOR/pubhtml?gid=1585526791&amp;single=true&amp;widget=true&amp;headers=false"
          ></iframe>
        </section>

        <section className="section">
          <h2>Supporting Documents Category C</h2>
          <ul>
            <li>
              <a
                href="https://drive.google.com/file/d/1fEpe-toKLeXac6oSejfLOevryEj1Hfxc/view"
                target="_blank"
                rel="noopener noreferrer"
              >
                Attachment C Category C Instructions
              </a>
              : Attachment B is a section of Program Opportunity Notice (PON)
              4614 for Community Heat Pump Systems that outlines Category B,
              which refers to Site-Specific Design Studies.
            </li>
            <li>
              <a
                href="https://drive.google.com/file/d/1vgEVKrHQCxyAcQNo-6jniGF4S7UA6s05/view"
                target="_blank"
                rel="noopener noreferrer"
              >
                Attachment C1 Category C Final Report Requirements
              </a>
              : The document outlines the requirements for a final report that
              will be posted on the New York State Energy Research and
              Development Authority (NYSERDA) website. The report is expected to
              address several questions related to the proposed community,
              technology, analytical methods, system design, business model, and
              impact of the project. The report should also include construction
              specifications, bid specs, and an investment-grade analysis of the
              economics associated with implementing/operating the system.
            </li>
            <li>
              <a
                href="https://drive.google.com/file/d/1o5WdLlT1iuXEF7asnDTN-Q9DPgj4RG4_/view"
                target="_blank"
                rel="noopener noreferrer"
              >
                Summary
              </a>
            </li>
            <li>
              <a
                href="https://drive.google.com/file/d/1icLAkFmwtTrcoNKlpTLCXSRQDEYzp6Ya/view"
                target="_blank"
                rel="noopener noreferrer"
              >
                Summary Revised
              </a>
            </li>
          </ul>
        </section>

        <section className="section flex-row items-start space-y-0 space-x-24 [&>figure]:space-y-4 [&>img]:w-1/2">
          <figure>
            <img
              src="/images/nyserdaApplication.png"
              alt="nyserda application"
            />
            <figcaption>Fig. 1 - NYSERDA Application</figcaption>
          </figure>
          <figure>
            <img
              src="/images/nyserdaEligibility.png"
              alt="nyserda eligibility"
            />
            <figcaption>Fig. 2 - NYSERDA Eligibility</figcaption>
          </figure>
        </section>
      </main>
    </>
  );
}
