import Head from "next/head";

export default function Overview() {
  return (
    <>
      <Head>
        <title>NYC Heat Recovery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main flex flex-col justify-start items-center space-y-24">
        <h1>Project Overview</h1>

        <section className="section">
          <h2>Motivation</h2>
          <p>
            The New York City subway is the number one form of public
            transportation in the city, with over two million people riding
            every day. However, the subway stations are known to have issues
            with high temperatures, especially during the warmer months of the
            year, usually hovering around 95 degrees Fahrenheit. This excessive
            heat is caused by a number of contributing phenomenons. Firstly, the
            heat sink effect causes heat to be transferred from surfaces like
            the pavement to immediately cooler areas, like a subway station.
            This is especially prevalent to subway stations since many are just
            one floor below ground level, and have stairways and entrances
            leading directly outside. The subway stations are also heated by the
            large amounts of heat given off by air conditioning systems used to
            cool the interior of the trains. The lack of air circulation is also
            a large factor in the high temperatures, causing heat to enter the
            subway and not leave. Finally, many stations are not air conditioned
            at all, with the exception of only a few such as Grand Central
            Terminal.
          </p>
        </section>

        <section className="section">
          <h2>Goals</h2>
          <p>
            NYC has implemented a target to reduce greenhouse gas emissions by
            80% by 2050. Transportation accounts for around 28% of the city’s
            total greenhouse gas emissions, and although a majority of those
            emissions come from cars, the subways do play a role in those
            emissions. Riding the subway is the more environmentally friendly,
            but the heating issues present deter ridership and contribute no
            solution to the carbon emissions of the stations. By using the heat
            present in subway stations as transferable energy for surrounding
            buildings, the subways can effectively decarbonize the subway
            system, while bringing in revenue and contributing positively to the
            city's greenhouse gas emissions reduction goal.
          </p>
        </section>

        <section className="section">
          <h2>Budget</h2>
          <p>
            The team was provided $10,000 from the project sponsor, Highmark.
            The CEO and Co-Founder, Richard Gebre, decided to give the group
            this amount to research and prototype this idea to bring it closer
            to reality. The budget was largely allocated to the construction of
            the scale model and the development of the Opportunity Map website
            tool. In addition to the design project, the team will aid Highmark
            by creating a roadmap for NYSERDA PON#4614 applications.{" "}
          </p>
        </section>

        <section className="section">
          <h2>Market Research</h2>
          <p>
            In order to finalize our station and building selection the team
            conducted several meetings with the MTA. This communication is
            helping us to ensure we corroborate their requirements for a
            sustainable model, gain insight to systems within subway stations
            through in-person meetings at the stations, and to ensure that our
            project is feasible both physically and economically.
            <br />
            <br />
            Future meeting with the building owners will help the team better
            understand limitations in construction/logistics.
          </p>
        </section>

        <section className="section">
          <h2>Schedule</h2>
          <p>
            The mechanical engineering program divides the senior capstone
            project into six phases. Project development is anticipated to meet
            the general objectives of each phase, which lasts for around five
            weeks. Each phase's work list, member duties, and deliverable due
            dates let the team keep track of progress.
          </p>
        </section>

        <section className="section">
          <h2>Motives</h2>
          <div className="img-col-2">
            <span>
              <img src="/images/efficiencyRating.jpg" alt="efficiency rating" />
              <div>
                <h3>Local Law 97</h3>
                <p>
                  Newly instated Local Law 97 places fines on NYC buildings that
                  fail to comply with decreasing emission caps. Starting in
                  2024, the emissions limits decrease every 5 years, until NYC
                  reaches its goal of being carbon neutral in 2050.
                </p>
              </div>
            </span>
            <span>
              <img src="/images/trainHeat.jpg" alt="train heat" />
              <div>
                <h3>Monetizing Heat</h3>
                <p>
                  The MTA has the possibility to monetize their excess heat,
                  providing a clean alternative to fossil fuels, the main fuel
                  source of boilers and steam cogeneration plants.
                </p>
              </div>
            </span>
          </div>
        </section>
      </main>
    </>
  );
}
