import Head from "next/head";

export default function ProgressPhase1() {
  return (
    <>
      <Head>
        <title>NYC Heat Recovery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Phase 1 Progress</h1>
        <section className="section">
          <p>
            In Phase I, the team concentrated on comprehending the issue at hand
            in order to develop workable solutions. The first phase of the
            project was regarded as the planning phase. The team was required to
            draft a project purpose statement and perform State of the Art
            Review. The team had to comprehend the project&apos;s requirements and
            specifications from all the stakeholders involved.
            <br />
            <br />
            The team&apos;s development is broken down here, week by week:
          </p>
        </section>

        <section className="section">
          <div className="w-full">
            <p>Meetings up to Sept 21st, 2022</p>
            <ul>
              <li>
                During these meetings the team has research various topics
                including London district energy system, Train as a pushing
                mechanism, amount of heat produced by trains/people/HVAC
                everyday, Temperature data from subway car testing, Air source
                heat pumps, and Hot water tanks in series, Learn more about MTA
                ventilation systems, Learn more about district hot water systems
                in NYC, and Heat in Subway tunnels over the seasons.
              </li>
              <li>Setting meetings with Advisor, Highmark, and MTA.</li>
              <li>
                Discussed station selections, building selection, budget, and
                NYSERDA.
              </li>
              <li>Action Items for future meeting:</li>
              <ul>
                <li>Determine how to measure heat in station</li>
                <li>Concept Generation for specific station/setup</li>
              </ul>
            </ul>
          </div>
        </section>

        <section className="section">
          <div className="w-full">
            <p>Meetings up to Oct 12th, 2022</p>
            <ul>
              <li>Phase 1 presentation</li>
              <ul>
                <li>Practice and prepare for presentation</li>
                <li>Review feedback</li>
              </ul>
              <li>Assigned and organize task for Phase 2</li>
              <ul>
                <li>Management</li>
                <li>Technical analysis</li>
                <ul>
                  <li>Hand calculations</li>
                  <li>Financial analysis</li>
                  <li>Field data</li>
                </ul>
                <li>Building correspondence</li>
                <li>Concept generation</li>
                <li>Website</li>
                <li>MTA correspondence</li>
              </ul>
              <li>Action Items for future meeting:</li>
              <ul>
                <li>Schedule second MTA meeting</li>
                <li>Sign Sponsor Agreement</li>
                <li>Finalize building selection</li>
                <li>Choose a building</li>
              </ul>
            </ul>
          </div>
        </section>

        <section className="section h-[50vh]">
          <p>
            Below is the Gantt Chart used throughout Phase 1. The chart was
            created in Microsoft Project and the group used it to break down the
            project phases into manageable parts. Microsoft Project then
            produced deadlines for when various tasks should be finished. The
            team used the Gantt Chart to ensure that deadlines for finishing
            various tasks were met and to plan their next course of action. The
            milestones for the project such as State of the Art Technology
            review and Concept Generation are on there and all other major due
            dates are listed on the Gantt Chart.
          </p>
          <iframe
            src="https://drive.google.com/file/d/11peKfW6gGOGO5tD2nDAo_dRg-tY9QLQo/preview"
            allow="autoplay"
          ></iframe>
        </section>

        <section className="section h-[50vh]">
          <p>
            Next is the Project Budget, it is quite challenging to specify a
            fully formed project budget in Phase 1. However, a preliminary
            budget was created to gain a sense of what is required to finish the
            project based on concept generation and market research. It will be
            more clear in phases two and three, when the technical analysis is
            finished. The sponsor of this project, Highmark, decided on the team
            budget and gave the group $10,000 to research and prototype this
            project. As seen in the chart we are allocating the budget for items
            like Transportation, Drawing and Modeling Software, and Equipment
            used for measuring and surveying for the stations.
          </p>
          <iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR7oeEQN-g2jP6OIEvAzRhq_X2h3noZURalZR1p25_dfX3eN_2Ga9QuH3se3-3HFZTQhPsWemWz3-Go/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false"></iframe>
        </section>
      </main>
    </>
  );
}
