import Head from "next/head";

export default function ProgressPhase2() {
  return (
    <>
      <Head>
        <title>NYC Heat Recovery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Phase 2 Progress</h1>
        <section className="section">
          <p>
            In Phase 2, the team concentrated on developing the preliminary
            Technical Analysis while finalizing the concept design.
          </p>
        </section>

        <section className="section">
          <div className="w-full">
            <p>Meeting up to Oct 12, 2022</p>
            <ul>
              <li>Meeting with MTA</li>
              <li>Phase 1 presentation</li>
              <ul>
                <li>Practice and prepare for presentation</li>
                <li>Review feedback</li>
              </ul>
              <li>Assigned and organize task for Phase 2</li>
              <ul>
                <li>Management</li>
                <li>Technical analysis</li>
                <ul>
                  <li>Hand calculations</li>
                  <li>Financial analysis</li>
                  <li>Field data</li>
                </ul>
                <li>Building correspondence</li>
                <li>Concept generation</li>
                <li>Website</li>
                <li>MTA correspondence</li>
              </ul>
              <li>Action Items for future meeting:</li>
              <ul>
                <li>Schedule second MTA meeting</li>
                <li>Sign Sponsor Agreement</li>
                <li>Finalize building selection</li>
                <li>Choose a building</li>
              </ul>
            </ul>
          </div>
        </section>

        <section className="section">
          <div className="w-full">
            <p>Meeting up to Oct 20th, 2022</p>
            <ul>
              <li>Meeting with MTA</li>
              <ul>
                <li>
                  <a
                    href="https://docs.google.com/document/d/19nQxMDMpVV6tdhawB_Cj9Sx8RAi9LkkG5MdN26hurFI/edit"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Link to Questions asked
                  </a>
                </li>
              </ul>
            </ul>
          </div>
        </section>

        <section className="section">
          <div className="w-full">
            <p>Meeting up to Oct 21st, 2022</p>
            <ul>
              {" "}
              <li>
                Based on meeting with MTA discuss with station to finalize
              </li>
              <li>Analyze documents sent over by MTA</li>
              <li>Deliverables and create separate team meetings</li>
              <ul>
                <li>Start website</li>
                <ul>
                  <li>Selected Google sites</li>
                </ul>
                <li>Field Data</li>
                <li>Technical Analysis</li>{" "}
              </ul>
              <li>
                Set up a meeting with Alderson Engineering (Principal at
                Anderson Engineering)
              </li>
              <ul>
                <li>Did study on subway geothermal application</li>
              </ul>
              <li>Feasibility of idea</li>
              <ul>
                <li>Specially for the winter</li>
              </ul>
              <li>ASHRAE</li>
              <ul>
                <li>
                  American Society of Heating, Refrigerating and
                  Air-Conditioning Engineers
                </li>
              </ul>
            </ul>
          </div>
        </section>

        <section className="section">
          <div className="w-full">
            <p>Meeting up to Oct 26, 2022</p>

            <ul>
              <li>Building and Station selection:</li>

              <ul>
                <li>Cooling station not main priority</li>
              </ul>

              <li>
                Technical analysis for phase 2 will be the various components of
                the heat transfer loop
              </li>
              <ul>
                <li>Heat Exchange in Station</li>

                <li>
                  Heat Exchange between MTA chiller loops and intermediary
                </li>
                <li>
                  Heat Exchange between intermediary loop and building water
                </li>
                <li>Compressor sizing if using air source heat pump</li>
                <li>Heat storage in building; stratified storage tanks</li>
                <li>Cost analysis</li>
                <li>Pump Sizing</li>
              </ul>
              <li>
                System Selection: Likely go forward with currently tempered
                station
              </li>
              <li>What to ask MTA:</li>
              <ul>
                <li>Details for heat transferred in air tempering system</li>
                <li>Temperature of fluid going to chiller</li>
              </ul>

              <li>Updated Organization of Phase II Teams</li>
              <ul>
                <li>Management (2) - Alysa, Drew</li>

                <ul>
                  <li>
                    Deliverable: Gantt Chart, Budget, Reserve meeting room long
                    term
                  </li>

                  <li>Gantt Chart</li>
                  <li>Track progress</li>
                  <li>Organization</li>
                  <li>Budgeting</li>
                  <li>Meeting scheduling</li>
                </ul>

                <li>Technical Analysis (All)</li>
                <ul>
                  <li>CAD Model (3-4) Drew, Erik, Scott, Aaron</li>

                  <ul>
                    <li>Deliverable: Matlab Analytical Models</li>

                    <li>ANSYS Framework - Drew</li>
                    <li>Trane Trace - Erik (if needed)</li>
                    <li>MATLAB - Aaron</li>
                    <li>AutoCAD - Aaron, Erik</li>
                    <li>ComSol - Scott</li>
                  </ul>
                  <li>Hand Calculations (2-3) - Erik, Anthony, Scott</li>
                  <ul>
                    <li>
                      Deliverable: Analytical models for existing station
                      concept
                    </li>

                    <li>Free Body Diagrams</li>
                  </ul>
                  <li>Financial Analysis (3-4) - Drew, Alysa, Aaron</li>
                  <ul>
                    <li>
                      Deliverable: Research current energy costs, NYSERDA
                      application paperwork, financial analysis for phase 2
                    </li>
                    <li>Review LL97 fines</li>
                  </ul>
                  <li>Field Data (2-3) - Angelina, Darlene, Erik, Colleen</li>
                  <ul>
                    Deliverable: Reach out to companies that can supply air data
                    monitoring systems
                    <li>Better data for developing model - Colleen</li>
                    <ul>
                      <li>Temperature</li>

                      <li>Materials</li>

                      <li>Airflow</li>

                      <li>Train frequency</li>
                    </ul>
                    <li>Anemometers</li>
                    <li>IR Thermometers</li>
                  </ul>
                </ul>

                <li>Building Correspondence (2-3) Drew, Colleen</li>
                <ul>
                  <li>
                    Deliverable: Look at buildings above unused stations; decide
                    concept to go forward with and then start pitching
                  </li>
                  <li>Identify prime buildings</li>
                  <li>Develop pitch deck</li>
                  <li>Land meetings</li>
                  <li>Direct to website</li>
                </ul>
                <li>Concept Generation (2-3) - Aaron, Scott</li>
                <ul>
                  <li>
                    Deliverable: Find out what needs to be presented for phase 2
                  </li>

                  <li>
                    Research current geothermal/district heating challenges in
                    NYC
                  </li>
                  <li>Compare, redo QFD</li>
                </ul>

                <li>Website (2-3) - Darlene, Anthony, Angelina</li>
                <ul>
                  <li>Deliverable: Continue adding info to site</li>

                  <li>Web design</li>

                  <li>Keep possibility for calculator</li>

                  <li>NYSERDA Roadmap</li>
                </ul>
                <li>
                  MTA Correspondence (one from each group) - Aaron, Erik,
                  Anthony, Drew
                </li>
                <ul>
                  <li>
                    Deliverable: Send email asking for air tempering system
                    details
                  </li>
                </ul>
              </ul>
            </ul>
          </div>
        </section>

        <section className="section h-[50vh]">
          <p>Below is the Gantt Chart used throughout Phase 2:</p>
          <iframe
            src="https://drive.google.com/file/d/1o-SkdcpVeYyD7xMjWvofDGgQ2vOjzRr3/preview"
            allow="autoplay"
          ></iframe>
        </section>
      </main>
    </>
  );
}
